Cleaner graffiti messaging
luciensadi/AwakeMUD pull request #652
Opened 2022-07-10 05:07 UTC by UndeadNappist

Removes quotation marks and 'is sprayed here' and replaces it with a single line at the top of the graffiti, supposedly.

2022-07-10 05:17 UTC, GarbageJet commented on src/act.other.cpp
> +        snprintf(buf, sizeof(buf), "Some people have sprayed here:", argument);
"Some people have sprayed here:" is weird. How about "Sprayed here," ?

2022-07-10 14:21 UTC, luciensadi commented
Every call to snprintf overwrites the buffer. You might be looking for `snprintf(ENDOF(buf), sizeof(buf) - strlen(buf),`, but even that wouldn't work quite right for this case, because if I'm reading this right, the next time someone sprays you'll have:
```
Sprayed here,  %s^n
Sprayed here,  %s^n
  %s^n```
What is your desired output? Can you test and see if you get that?

2022-07-10 17:20 UTC, UndeadNappist commented
Desired output is
```
Sprayed here,
   %s^n
   %s^n
```
Currently just prints
```
   %s^n
   %s^n
```

2022-07-11 18:50 UTC, UndeadNappist commented
![image](https://user-images.githubusercontent.com/7409796/178336882-ba11b8fe-f99c-4dab-bb96-a64be8a5e340.png)

Works correctly now.

2022-07-12 14:14 UTC, luciensadi requested changes
Looks a lot better, just a few nits.

2022-07-12 14:14 UTC, luciensadi commented on src/act.other.cpp
> +      snprintf(buf, sizeof(buf), "^g   %s^n", argument);
This is the item name itself, it should be left as the piece of graffiti string since it doesn't show up in the room.

2022-07-12 14:14 UTC, luciensadi commented on src/act.other.cpp
> +      send_to_char("You spray graffiti into the room.\r\n", ch);
A 'room' is an artificial concept that doesn't apply in a lot of situations, a more generic message like "You tag the area" might fit better here.

2022-07-14 00:57 UTC, UndeadNappist commented on src/act.informative.cpp
> +            send_to_char(ch, "^gSprayed here,^n\r\n");
Nothing. Item goes on top.
![image](https://user-images.githubusercontent.com/7409796/178862032-50bf9620-8399-4634-b1b6-a0c429490971.png)

2022-07-14 02:46 UTC, merged

2022-07-14 02:46 UTC, luciensadi commented
Looks good, thanks!