Show room on gridguide arrival
luciensadi/AwakeMUD pull request #673
Opened 2022-09-10 20:48 UTC by jdevnull

Quality of life change: when gridguide arrives at its destination, automatically show the room to vehicle occupants.

-Khai

2022-09-16 02:52 UTC, luciensadi requested changes

2022-09-16 02:52 UTC, luciensadi commented on src/act.drive.cpp
> +          if (!IS_NPC(ch)) {
A check here for being flagged screenreader would be good, reader users have definitely asked for the ability to stifle automatic room description delivery.

2022-09-16 02:52 UTC, luciensadi commented on src/act.drive.cpp
> +  look_at_room(ch, 0, 0)
A check here would be good too! IIRC it's something along the lines of `if (!PRF_FLAGGED(ch, PRF_SCREENREADER))`

2022-09-16 19:37 UTC, jdevnull commented
Done!

2022-09-17 20:21 UTC, luciensadi commented
Perfect, thanks!

2022-09-17 20:21 UTC, merged